# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' getCIndexFromCoords returns the raw h3 index from a lat, lon, and resolution
#' @param lat latitude in degrees
#' @param lon longitude in degrees
#' @param resolution resolution, higher is more granular
getCIndexFromCoords <- function(lat, lon, res) {
    .Call(`_h3r_getCIndexFromCoords`, lat, lon, res)
}

#' getIndexFromCoords returns the h3 index from a lat, lon, and resolution
#' @param lat latitude in degrees
#' @param lon longitude in degrees
#' @param resolution resolution, higher is more granular
getIndexFromCoords <- function(lat, lon, resolution) {
    .Call(`_h3r_getIndexFromCoords`, lat, lon, resolution)
}

#' getBoundingHexFromCoords returns the h3 bounding hex from a lat, lon and resolution
#' @param lat latitude in degrees
#' @param lon longitude in degrees
#' @param resolution resolution, higher is more granular
getBoundingHexFromCoords <- function(lat, lon, resolution) {
    .Call(`_h3r_getBoundingHexFromCoords`, lat, lon, resolution)
}

#' getBoundingHexFromIndex takes an h3 index and returns the corresponding bounding hex
#' @param index h3 index as a hex representation character vector. See \code{\link{getIndexFromCoords}}
getBoundingHexFromIndex <- function(index) {
    .Call(`_h3r_getBoundingHexFromIndex`, index)
}

#' h3_string_to_int takes an h3 index represented as a hexadecimal string and returns the integer format.
#' @param index h3 index as a hex representation character vector. See \code{\link{getIndexFromCoords}}
h3_string_to_int <- function(index) {
    .Call(`_h3r_h3_string_to_int`, index)
}

#' h3_int_to_string takes an h3 integer representation and returns the string format. 
#' @param index as an integer representation. 
h3_int_to_string <- function(index) {
    .Call(`_h3r_h3_int_to_string`, index)
}

